### ISSUE TITLE
Add run information to batch 3

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/sequencing-data#9]
As requested by @cymon, the run information files for batch 3 should be created. 

https://github.com/emo-bon/sequencing-data/tree/main/shipment/batch-003-0
https://github.com/emo-bon/sequencing-data/tree/main/shipment/batch-003-1
https://github.com/emo-bon/sequencing-data/tree/main/shipment/batch-003-2

@cpavloud

**Comment by kmexter** [comment]
Can I also ask to look at the names of the files that are created for these folders?
If you look at batch-001 you see a run-information-batch-001, run-information-batch-001_column-descriptions, ena-accession-numbers-batch-001, and finally properties-batch-001.yml (ignore the file batch-001.ttl)
All batch folders need to have these files with the same filename, contents, and layout. 
If you need to make changes for batch 3, then we have to coordinate that with the files in batch 001 and 2

**Comment by cpavloud** [comment]
At the moment, only the list-of-samples-batch-003-X.csv and the properties-batch-003.yml is in every batch 3 folder. The  properties-batch-003.yml will not be changed.

The run-information-batch-003_column-descriptions will be a file copied from batch 1 and batch 2 folders. It will not be changed. Although some changes DO need to happen (see https://github.com/emo-bon/sequencing-data/issues/8)

The ena-accession-numbers-batch-003 will be created after we have sample accessions numbers.

**Comment by cpavloud** [comment]
Ok, so I have created and uploaded the run information for batch [3.0](https://github.com/emo-bon/sequencing-data/blob/main/shipment/batch-003-0/run-information-batch-003-0.csv), [3.1](https://github.com/emo-bon/sequencing-data/blob/main/shipment/batch-003-1/run-information-batch-003-1.csv) and [3.2](https://github.com/emo-bon/sequencing-data/blob/main/shipment/batch-003-2/run-information-batch-003-2.csv)

@cymon please let me know if you need anything else at this point. If not, I will close the issue.
